# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama2 7B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama2"
flavor = "7B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "models/Llama-2-7b-hf/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 128
seq_len = 2048
warmup_steps = 200  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 1000
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1  # -1
tensor_parallel_degree = 1  # dp-only would be sufficient for 7B
compile = false
dataset = "c4_test"

[experimental]
context_parallel_degree = 1 
pipeline_parallel_degree = 8

[checkpoint]
enable_checkpoint = true
folder = "llama/checkpoint"
interval_type = "steps"
interval = 200
model_weights_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
